# version: '3.6'
# services:
#   db:
#     image: postgres:latest
#     env_file:
#       - env/postgres.env
#     ports:
#       - 54320:5432
#     networks:
#       - nestjs-auth-intranet
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#   redis:
#     image: redis/redis-stack-server:7.2.0-v6
#     env_file:
#       - env/redis.env
#     ports:
#       - 6379:6379
#     networks:
#       - nestjs-auth-intranet
#     healthcheck:
#       test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
#     volumes:
#       - redis_data:/data
#   zookeeper:
#     image: bitnami/zookeeper:latest
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: bitnami/kafka:latest
#     ports:
#       - '9092:9092'
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       ALLOW_PLAINTEXT_LISTENER: 'yes'
#     depends_on:
#       - zookeeper
# volumes:
#   postgres_data:
#   redis_data:
# networks:
#   nestjs-auth-intranet:
#     name: nestjs-auth-intranet
#     driver: bridge

version: '3.6'
services:
  db:
    image: postgres:latest
    env_file:
      - env/postgres.env
    ports:
      - 5432:5432
    networks:
      - nestjs-auth-intranet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    env_file:
      - env/redis.env
    ports:
      - 6379:6379
    networks:
      - nestjs-auth-intranet
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
networks:
  nestjs-auth-intranet:
    name: nestjs-auth-intranet
    driver: bridge
